# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 爱奇艺会员签到

on:
  workflow_dispatch:
  schedule:
     - cron: "5 16 * * *"
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/GB-png/test.git ~/JavaScript
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【爱奇艺会员签到】'
        run: |
          cd ~/JavaScript
          node Task/iqiyi.js
        env:
          iQIYI_COOKIE: ${{ secrets.iQIYI_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}          
